version: "3.8"
services:

  scrapper_server:
    build: ./
    container_name: scrapper_server
    ports:
      - 8888:80
    networks:
      - app-network


networks:
  app-network:
    driver: bridge