version: "3.8"
services:

  telegram-bot:
    build: ./src/telegram-bot
    container_name: telegram-bot
    restart: unless-stopped
    networks:
      - ai-product-news-network
    depends_on:
      - ml

  ml:
    build: ./src/ml
    container_name: ml
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - ai-product-news-network

networks:
  ai-product-news-network:
    driver: bridge
